/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseConfirmDialog: typeof import('./components/Base/BaseConfirmDialog.vue')['default']
    BaseDialog: typeof import('./components/Base/BaseDialog.vue')['default']
    LoaderBar: typeof import('./components/App/loaderBar.vue')['default']
    MenuBar: typeof import('./components/App/menuBar.vue')['default']
    NotFound: typeof import('./components/App/NotFound.vue')['default']
    Notification: typeof import('./components/App/notification.vue')['default']
    NotificationBar: typeof import('./components/App/notificationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
